### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by ambs** [nunovieira220/pln_apirest#22]
Criar forma de cada módulo (de cada serviço) ter uma pasta t/ com testes que verifiquem se os serviços estão online e a funcionar.

Como convém que estes testes funcionem localmente, enquanto se desenvolve, e também no servidor, as scripts de teste podem usar variáveis de ambiente para o hostname e a porta:

``````
    $ export SPLINE_HOST=nlp.di-um.org
    $ export SPLINE_PORT=80
```````
e os testes começam por
```````
   my $host = $ENV{SPLINE_HOST} || 'localhost';
   my $port = $ENV{SPLINE_PORT} || 3000;
```````

Se os testes fossem definidos no XML, e a partir daí gerados os ficheiros .t, seria ouro sobre azul! :)

**Comment by nunovieira220** [comment]
Boa noite, professor.

Admito que não percebi bem a parte dos exports para funcionar localmente. Os testes não são sempre corridos localmente?

Meter os testes a serem gerados automaticamente parece-me fácil seja com código integral seja com pares input/output. Tenho de ver como ficaria um teste para um serviço já existente, tipo tokenizer.

Vou entretanto explicar o XML para avançar com o artigo.

Cumprimentos, Nuno Vieira.


A 07/04/2015, às 19:43, Alberto Simões <notifications@github.com> escreveu:

**Comment by ambs** [comment]
Olá

Os testes para desenvolvimento são sempre corridos localmente.
Mas para garantirmos que o servidor também está 100% funcional, também 
dá jeito que possámos executar os testes sobre o serviço "final".

Caso contrário estamos sempre na dúvida: será que os módulos instalaram 
corretamente? Será que não há nenhuma biblioteca a falhar? coisas desse 
género.

Abraço
Alberto

**Comment by nunovieira220** [comment]
Bom dia, professor.

Mas então o que o professor quer é que eu gere testes para o módulo CPAN e não para cada um, certo? Porque se fizer testes individuais para cada um, só estou a ver como se fará localmente. O problema aqui é não saber como é que os testes vão ser executados.

Cumprimentos, Nuno Vieira.


A 08/04/2015, às 09:04, Alberto Simões <notifications@github.com> escreveu:

**Comment by ambs** [comment]
A ver se me faço explicar :-)

Imagina o módulo para tokenização.
O próprio módulo sabe:
  - qual a route em que ficará instalado
  - quais os parametros necessários
  - quais os resultados supostos

Então, pode usar um módulo tipo HTTP::Tiny para aceder ao servidor (em 
modo localhost ou no per-fide), submeter um texto, obter o resultado, e 
verificar se esse teste passa.

Claro que estes testes não funcionam de forma independente, sem acesso 
ao servidor. Portanto, não são testes tipo CPAN. Apenas uma forma de 
garantir que o módulo é devidamente instalado pelo servidor.

Até pode ir para uma pasta com nome diferentes, tipo xt (extra tests).

consegui explicar-me? :)

**Comment by nunovieira220** [comment]
Eu entendo isso tudo. Mas esse tipo de problema não seria resolvido se se criasse testes ao nível do módulo CPAN que se vai criar? Ele lá dentro invoca a ligação ao servidor (neste caso até está localhost mas convém mudar-se isso depois e já usa o Tiny).

Se se criasse testes para esse módulo, daria para testar todos os módulos tanto juntos como separados (estou a assumir que dá para dentro da pasta t dê para dividir por directorias de serviços). Adicionar testes era fácil sendo que só se adicionava uma nova directoria ou um simples ficheiro para testar. A mim, pelo menos, pareceu-me a maneira mais fácil e não seria preciso fazer grandes "manobras". 

Quanto ao pequeno texto a falar sobre a info do XML, já o escrevi lá.

Se o que eu percebi está correcto, quer que eu faça um forcing e insira já a parte dos testes nos próximos dias? Estava planeado agora ver aquela parte das moedas e do histórico mas faço facilmente um forcing para isso dos testes.

Cumprimentos, Nuno Vieira.


A 08/04/2015, às 11:55, Alberto Simões <notifications@github.com> escreveu:

**Comment by ambs** [comment]
Acho que um de nós não está a fazer-se entender :-)
Vamos tentar sistematizar isto:

   1. Temos o módulo/App Dancer
   2. Temos cada um dos módulos/DSL de serviços
   3. Temos o módulo genérico de cliente

Ora, o que eu estava a sugerir é que os testes fossem adicionados nos módulos de serviços (2), porque são estes módulos que sabem a API que oferecem.

O módulo de servidor (1) deve ser genérico para se configurar de acordo com os módulos/DSL existentes -- o que já acontece.

O módulo cliente (3) também deve ser genérico, perguntando ao servidor quais os métodos disponíveis, e tornando-os invocáveis via HTTP.

Ou seja, parece-me que o sítio certo dos testes seria nos módulos (2). Era a isso que me estava a referir.

Abraço
Alberto

**Comment by nunovieira220** [comment]
Boa tarde, professor.

Sim, por lógica tem mais sentido os testes estarem inseridos em cada módulo e eu entendo isso. A minha dúvida aqui é perceber, se os testes forem colocados lá, como é suposto eles funcionarem. Vai ser preciso ir um a um testar? Se sim, não será tudo local?

Cumprimentos, Nuno Vieira.
 

A 09/04/2015, às 11:43, Alberto Simões <notifications@github.com> escreveu:

**Comment by ambs** [comment]
Oi

Em princípio permitiria:
   - que o programador de um módulo pudesse testar esse módulo apenas (o make test arrancaria uma instância do servidor, carregando apenas esse módulo, e seria testado)
   - estando definido o ENV com o servidor, o make test usaria esse servidor para testar

Claro que se quiseres testar *todos* os módulos terás de ir a cada um deles testá-lo individualmente. Mas enquanto que *neste momento* nos dá jeito testá-los a todos, no futuro dará jeito testar apenas aquele que se está a implementar...

Acho eu :)

**Comment by nunovieira220** [comment]
Sim, eu entendo a ideia. Basicamente o make test vai testar o modulo via URL/server e não via módulo directamente. Vou tentar perceber como funciona aquilo do export e do ENV e até mesmo a parte dos testes (já me esqueci de alguns pormenores). A ver se consigo pelo menos inserir isso no artigo (a estrutura XML).

Cumprimentos, Nuno Vieira.


A 09/04/2015, às 14:45, Alberto Simões <notifications@github.com> escreveu:

**Comment by nunovieira220** [comment]
Boa tarde, professor.

Queria perguntar-lhe se todos os testes que se irão fazer aos serviços terão por base dar um input e verificar se o output faz match com o indicado. Porque se assim fosse, era bem facil fazer uma estrutura XML para isso.

Se existir outro tipo de testes, como seriam? Pensei em testes de conexão mas os próprios testes de input/output conseguiam verificar isso.

Cumprimentos, Nuno Vieira.


A 09/04/2015, às 15:42, Nuno Vieira <nunovieira220@gmail.com> escreveu:

**Comment by ambs** [comment]
Eu acho que sim, input/output, embora em casos mais complicados, como o 
tal dicionário de tradução do NATools, irá ficar algo limitado.

Acho que devemos ir tentando incluir mais serviços no sentido de também 
percebermos o que faz falta :)

**Comment by nunovieira220** [comment]
Sim, o problema é mesmo a entrega do artigo ser tão próxima. Incorporar isto dos testes lá, seria, sem dúvida, algo de valor. De qualquer maneira eu vou criar com pares input/output, se mais tarde for necessário alterar, altera-se.

Cumprimentos, Nuno Vieira.


A 10/04/2015, às 19:32, Alberto Simões <notifications@github.com> escreveu:

**Comment by nunovieira220** [comment]
Boa tarde, professor.

Envio-lhe este email para lhe dizer que se calhar a abordagem da criação dos testes baseada em input/output não é a melhor. Considerando que estamos a trabalhar com estruturas (como output) mesmo que em JSON, fica difícil acertar no resultado final usando apenas XML. Se já com Perl não é fácil, pior será com XML onde não há maneira de criar uma estrutura fixa.

Apesar de não gostar muito da abordagem, a solução seria algo como ter os parâmetros um a um (isto é igual) e depois ter um campo para escrever o teste como, por exemplo: 

<test_code>ok(x == y, "Simple input-output test");</test_code>

E poderia ter múltiplos testes com o mesmo contexto. Que acha, professor?

Cumprimentos, Nuno Vieira.


A 10/04/2015, às 19:39, Nuno Vieira <nunovieira220@gmail.com> escreveu:

**Comment by nunovieira220** [comment]
Optei pela estratégia que meti aqui mas com uma divisão de testes melhor definida. Mais logo ou amanha acrescentarei no documento do artigo e o professor conseguirá ver como ficou feito e se concorda/discorda com a ideia proposta.

A geração dos testes está feita também seguindo aquele formato. Se calhar ainda devo ter de fazer alguns testes mas até agora pareceu-me bem.

Eu só quero fazer uma pequena pergunta pois procurei na net e não encontrei. É possível escrever ficheiros com a função open que não sejam readonly? Pelo que li existe uma solução com o sysopen mas não queria estar a alterar em todos os lados.

Cumprimentos, Nuno Vieira.


A 11/04/2015, às 17:34, Nuno Vieira <nunovieira220@gmail.com> escreveu:

**Comment by ambs** [comment]
Olá

Vou tentar perceber ao certo o que fizeste, mas qualquer abordagem, como início, é boa! Depois vai-se melhorando.

Não percebi a pergunta do ReadOnly. Queres escrever um ficheiro e ao mesmo tempo, andar a procurar no mesmo ficheiro? Isso não é uma "boa" prática....

**Comment by nunovieira220** [comment]
Boa tarde, professor.

Não, isso do readonly é porque depois quero editar o ficheiro num editor e ele não me permite faze-lo. Presumo que seja por causa do método de escrita que usei no Perl.

Aproveito para dar um update do que tenho feito. Os testes estão feitos (pelo menos para os casos mais simples) e já inseri a porção do XML e do teste resultado no documento do artigo. Inseri também na interface a informação relativa aos custos (só para as ferramentas e o tamanho do texto, ainda não adicionei a opção do user ver o histórico e as suas moedas).

O objectivo dos próximos dias será acabar o artigo (acaba sexta, certo?) e adiantar esta parte das moedas para depois atacar o problema do nat-create que me parece cabeludo.

Acho que é tudo.

Cumprimentos, Nuno Vieira.


A 12/04/2015, às 17:36, Alberto Simões <notifications@github.com> escreveu:

**Comment by ambs** [comment]
OK, eu vou imprimir o estado atual do artigo para ver melhor a estrutura e tentar dar-lhe um "fim" :-) se dissermos que temos alguma coisa que também não está 100%, não há problema.

Quanto aos ficheiros criados pelo open, isso é estranho. Vê o que te retorna o "umask" no perl, e possivelmente podes usá-lo para alterar as permissões "default".

abc

**Comment by nunovieira220** [comment]
Ok, professor.

Entretanto se eu poder dar uma mãozinha nisso, agradecia que me dissesse.

Cumprimentos, Nuno Vieira.


A 12/04/2015, às 18:00, Alberto Simões <notifications@github.com> escreveu:

**Comment by ambs** [comment]
Já deste mais que uma mãozinha, eu é que tenho sido um baldas...

**Comment by nunovieira220** [comment]
Boa tarde, professor.

Queria só fazer-lhe uma pergunta rápida em relação ao Dancer Database. É possível fazer quick selects sem ele retornar uma das colunas? Se não, há maneira de fazer, mesmo com o prepare e execute e o resto, criando um array de rows (não queria um hash aqui).

Cumprimentos, Nuno Vieira.


A 12/04/2015, às 19:36, Alberto Simões <notifications@github.com> escreveu:

**Comment by ambs** [comment]
Oi

Yep:

The options you can provide are:

<https://metacpan.org/pod/Dancer::Plugin::Database::Core::Handle#columns>|columns|

    An arrayref of column names to return, if you only want certain
    columns returned


Em todo o caso:

    my $statement = database->prepare("SELECT ... ");

Abc

**Comment by nunovieira220** [comment]
Exacto, eu já imaginava que existisse alguma opção incorporada mas não estava a encontrar nada que me ajudasse a chegar lá. 

Com isto aproveito para informar o professor que já criei a pagina que mostra as moedas que ainda tem e o histórico de pedidos a partir do token. 

Agradeço a resposta rápida.

Cumprimentos, Nuno Vieira.


A 13/04/2015, às 19:41, Alberto Simões <notifications@github.com> escreveu:
